---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: ubuntu1404

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check groups
  - ${DOCKER} groups travis_admin | grep travis_admin
  - ${DOCKER} groups travis_admin | grep travis_group
  - ${DOCKER} groups travis_admin2 | grep travis_admin
  - ${DOCKER} groups travis_admin2 | grep travis_group
  - ${DOCKER} groups travis_normal | grep travis_normal
  - ${DOCKER} groups travis_normal | grep travis_group

  - ${DOCKER} egrep -q -i "^usergroup1" /etc/group
  - ${DOCKER} egrep -q -i "^usergroup2" /etc/group

  # Check removed groups
  - ${DOCKER} egrep -i "^dummy_group1" /etc/group | wc -l | grep 0

  # Check users
  - ${DOCKER} id -u travis_admin
  - ${DOCKER} id -u travis_admin2
  - ${DOCKER} id -u travis_normal

  # Check removed users
  - >
    ${DOCKER} id -u dummy1
    && (echo "User is removed: fail" && exit 1)
    || (echo 'User is removed: pass' && exit 0)
  - >
    ${DOCKER} id -u dummy2
    && (echo 'User is removed: fail' && exit 1)
    || (echo 'User is removed: pass' && exit 0)

  # sudo
  - ${DOCKER} sudo test -e /etc/sudoers.d/10-ansible-managed
  - ${DOCKER} sudo grep travis_admin /etc/sudoers.d/10-ansible-managed

  # ssh
  - ${DOCKER} sudo egrep -i 'key1' /home/travis_admin2/.ssh/authorized_keys
  - ${DOCKER} sudo egrep -i 'key2' /home/travis_admin2/.ssh/authorized_keys

  # Ensure ssh is removed from removed users
  - ${DOCKER} [ ! -d /home/dummy1 ]
  - ${DOCKER} [ ! -d /home/dummy2 ]

  # sshd_config
  - ${DOCKER} grep 'PasswordAuthentication no' /etc/ssh/sshd_config
  - ${DOCKER} grep 'PermitRootLogin no' /etc/ssh/sshd_config
  - ${DOCKER} grep 'Port 2828' /etc/ssh/sshd_config

after_failure:
  - ${DOCKER} ansible --version
  - ${DOCKER} cat /etc/passwd
  - ${DOCKER} cat /etc/group
  - ${DOCKER} cat /etc/sudoers.d/10-ansible-managed
  - ${DOCKER} cat /etc/ssh/sshd_config
  - ${DOCKER} cat tail -n150 /var/log/syslog
  - ${DOCKER} cat ls -l /home/dummy1/
  - ${DOCKER} cat /home/dummy1/.ssh/authorized_keys

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
